import { callGeminiAPI, extractJSONFromResponse } from '@lib/api/gemini';
import type {
  Citation,
  ContentPayload,
  CreatorAgent,
  CreatorProposal,
  GrowthPayload,
  MonetizationPayload,
  ResearchPayload
} from '@lib/types/creator';

export const RESEARCH_MCP_ALLOWLIST = [
  'web.search',
  'web.fetch',
  'analytics.export',
  'internal.docs.search'
];

function safeCitations(topic: string): Citation[] {
  return [
    {
      title: `${topic} trend overview`,
      url: `https://www.google.com/search?q=${encodeURIComponent(topic)}`,
      note: 'Broad trend lookup'
    }
  ];
}

export async function generateResearchPayload(
  input: string
): Promise<ResearchPayload> {
  const prompt = `You are Buzzwin ResearchAgent.
Return JSON only.

Input topic: ${input}

Return schema:
{
  "topic": "...",
  "summary": "...",
  "audience": "...",
  "keyAngles": ["...", "...", "..."],
  "outline": ["...", "...", "..."],
  "citations": [
    { "title": "...", "url": "https://...", "note": "..." }
  ]
}

Rules:
- Provide 3-5 keyAngles.
- Provide 4-8 outline bullets.
- Include at least 2 citations with valid https URLs.
- Keep it practical and creator-focused.`;

  try {
    const raw = await callGeminiAPI(prompt, 1200, 0.4);
    const parsed = extractJSONFromResponse(raw) as Partial<ResearchPayload>;

    const citations = Array.isArray(parsed.citations)
      ? parsed.citations.filter(
          (c) =>
            typeof c?.title === 'string' &&
            typeof c?.url === 'string' &&
            c.url.startsWith('http')
        )
      : [];

    return {
      topic: parsed.topic || input,
      summary:
        parsed.summary ||
        `Research brief for ${input} with practical angles and sources.`,
      audience: parsed.audience || 'Busy creators and operators',
      keyAngles:
        Array.isArray(parsed.keyAngles) && parsed.keyAngles.length
          ? parsed.keyAngles.slice(0, 5)
          : [
              'Problem framing',
              'Actionable framework',
              'Examples and pitfalls'
            ],
      outline:
        Array.isArray(parsed.outline) && parsed.outline.length
          ? parsed.outline.slice(0, 8)
          : ['Hook', 'Context', 'Framework', 'Action checklist'],
      citations: citations.length ? citations : safeCitations(input),
      mcpAllowlist: RESEARCH_MCP_ALLOWLIST
    };
  } catch {
    return {
      topic: input,
      summary: `Research brief for ${input}.`,
      audience: 'Busy creators and operators',
      keyAngles: ['Problem framing', 'Actionable framework', 'Examples'],
      outline: ['Hook', 'Context', 'Framework', 'Checklist'],
      citations: safeCitations(input),
      mcpAllowlist: RESEARCH_MCP_ALLOWLIST
    };
  }
}

export async function generateContentPayload(
  input: string,
  linkedProposalId?: string
): Promise<ContentPayload> {
  const prompt = `You are Buzzwin ContentAgent.
Return JSON only.

Input brief:\n${input}

Schema:
{
  "briefTitle": "...",
  "draftTitle": "...",
  "excerpt": "...",
  "draftMarkdown": "# ...",
  "tags": ["..."],
  "headlineVariants": ["...", "...", "..."]
}

Rules:
- Draft markdown 500-900 words.
- Keep paragraphs concise and practical.
- Provide 3 headlineVariants.
- Return valid JSON only.`;

  try {
    const raw = await callGeminiAPI(prompt, 2200, 0.55);
    const parsed = extractJSONFromResponse(raw) as Partial<ContentPayload>;

    return {
      briefTitle: parsed.briefTitle || 'Research brief',
      draftTitle: parsed.draftTitle || 'Draft post',
      excerpt: parsed.excerpt || 'Draft generated by ContentAgent.',
      draftMarkdown:
        parsed.draftMarkdown ||
        `# Draft\n\n${input}\n\n## Next\n- Edit\n- Approve\n- Publish`,
      tags: Array.isArray(parsed.tags) ? parsed.tags.slice(0, 6) : ['creator'],
      headlineVariants: Array.isArray(parsed.headlineVariants)
        ? parsed.headlineVariants.slice(0, 5)
        : ['Draft headline A', 'Draft headline B', 'Draft headline C'],
      linkedProposalId
    };
  } catch {
    return {
      briefTitle: 'Research brief',
      draftTitle: 'Draft post',
      excerpt: 'Draft generated by ContentAgent.',
      draftMarkdown:
        `# Draft\n\n${input}\n\n## Next\n- Edit\n- Approve\n- Publish`,
      tags: ['creator'],
      headlineVariants: ['Draft headline A', 'Draft headline B', 'Draft headline C'],
      linkedProposalId
    };
  }
}

export function generateGrowthPayload(input: string): GrowthPayload {
  return {
    hypothesis: `Testing headline and timing effects for: ${input}`,
    channel: 'blog',
    headlineVariants: [
      `How to ${input}`,
      `${input}: a practical playbook`,
      `What changed when we tried ${input}`
    ],
    sendTimeOptionsISO: [
      new Date(Date.now() + 60 * 60 * 1000).toISOString(),
      new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString()
    ]
  };
}

export function generateMonetizationPayload(input: string): MonetizationPayload {
  return {
    angle: `Sponsor fit ideas for ${input}`,
    sponsors: [
      {
        name: 'Notion',
        reason: 'Strong creator and productivity overlap',
        website: 'https://www.notion.so'
      },
      {
        name: 'Canva',
        reason: 'Audience overlap for creator workflows',
        website: 'https://www.canva.com'
      }
    ],
    pitchDraft:
      `Hi {{brand}},\n\nWe are exploring a creator-focused story on ${input} and see audience fit with your product. If useful, we can share concept notes and metrics.\n\nBest,\nBuzzwin`,
    requiresHumanApproval: true
  };
}

export async function buildProposalFromAgent(args: {
  agent: CreatorAgent;
  input: string;
  createdBy: string;
  linkedProposalId?: string;
  source?: 'manual' | 'cron' | 'event';
  promptHash?: string;
  toolCallSummary?: string;
}): Promise<Omit<CreatorProposal, 'id'>> {
  const {
    agent,
    input,
    createdBy,
    linkedProposalId,
    source = 'manual',
    promptHash,
    toolCallSummary
  } = args;

  if (agent === 'research') {
    const payload = await generateResearchPayload(input);
    return {
      type: 'brief',
      agent,
      status: 'pending',
      title: `Research brief: ${payload.topic}`,
      summary: payload.summary,
      payload,
      createdAt: new Date(),
      createdBy,
      source,
      promptHash: promptHash ?? null,
      toolCallSummary:
        toolCallSummary ?? `MCP allowlist: ${RESEARCH_MCP_ALLOWLIST.join(', ')}`,
      reviewedBy: null,
      reviewedAt: null,
      reviewNotes: null,
      editedContent: null,
      linkedDraftId: linkedProposalId ?? null
    };
  }

  if (agent === 'content') {
    const payload = await generateContentPayload(input, linkedProposalId);
    return {
      type: 'draft',
      agent,
      status: 'pending',
      title: payload.draftTitle,
      summary: payload.excerpt,
      payload,
      createdAt: new Date(),
      createdBy,
      source,
      promptHash: promptHash ?? null,
      toolCallSummary: toolCallSummary ?? 'ContentAgent draft synthesis',
      reviewedBy: null,
      reviewedAt: null,
      reviewNotes: null,
      editedContent: null,
      linkedDraftId: linkedProposalId ?? null
    };
  }

  if (agent === 'growth') {
    const payload = generateGrowthPayload(input);
    return {
      type: 'experiment',
      agent,
      status: 'pending',
      title: 'Growth experiment proposal',
      summary: payload.hypothesis,
      payload,
      createdAt: new Date(),
      createdBy,
      source,
      promptHash: promptHash ?? null,
      toolCallSummary: toolCallSummary ?? 'GrowthAgent variant generation',
      reviewedBy: null,
      reviewedAt: null,
      reviewNotes: null,
      editedContent: null,
      linkedDraftId: linkedProposalId ?? null
    };
  }

  const payload = generateMonetizationPayload(input);
  return {
    type: 'sponsor_idea',
    agent,
    status: 'pending',
    title: 'Monetization shortlist',
    summary: payload.angle,
    payload,
    createdAt: new Date(),
    createdBy,
    source,
    promptHash: promptHash ?? null,
    toolCallSummary: toolCallSummary ?? 'MonetizationAgent sponsor suggestions only',
    reviewedBy: null,
    reviewedAt: null,
    reviewNotes: null,
    editedContent: null,
    linkedDraftId: linkedProposalId ?? null
  };
}
